server :
  port : 5005 #gin listen to this port #http server port
  runMode : debug #loggs all the request and detailed errors thats one of gin mode
logger:
  filePath: ../logs/logs.log #loggs are saved here
  Encoding: json
  level: debug
  output: file
cores: #which frontends can call your backend from browsers Cross-Origin Resource Sharing
   allowOrigins: "*" #allow all origins and browser permission
   #all are used locally 
postgres: #persistant data
 host: localhost
 
 ports:
  - "5432:5432"
  - "6379:6379"
 password : admin
 dbname : book_store_db
 sslmode: disable
 maxidleconnections : 15
 maxopenconnections : 100
 connmaxtimeout : 5
redis: #fast in memory data with key value
 host: redis_container #internal networkname
 port: 6379
 password: password
 db: 0 #put the cash in room 0 (it has 16)
 dialTimeout: 5
 readTimeout: 5
 writeTimeout: 5
 minidleconnections: 100 #even if we had zero active users
 Idlecheckfrequency : 
 poolsize: 5000 #Max number of Redis connections large pool size for testing
 pooltimeout: 240 #How long to wait for a free connection
